apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: webapp
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
